apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
  - name: giropops-pod
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: giropops-secret-1
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: giropops-secret-1
          key: password
